// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtT4cE20y8zXptPBik-tABVpBaB6xNDEU',
    appId: '1:661720149477:web:b2a5139eafba67966c930c',
    messagingSenderId: '661720149477',
    projectId: 'nha-224',
    authDomain: 'nha-224.firebaseapp.com',
    storageBucket: 'nha-224.firebasestorage.app',
    measurementId: 'G-MHLFMJTQJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANacDiw2V76Jubyq00R_phLIQC6gf7Lyg',
    appId: '1:661720149477:android:9426f357b61d7eac6c930c',
    messagingSenderId: '661720149477',
    projectId: 'nha-224',
    storageBucket: 'nha-224.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4psVHA3mLfAx8hd9TT57kAvSul66bprU',
    appId: '1:661720149477:ios:67acc5862ea348536c930c',
    messagingSenderId: '661720149477',
    projectId: 'nha-224',
    storageBucket: 'nha-224.firebasestorage.app',
    iosBundleId: 'com.example.depiFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4psVHA3mLfAx8hd9TT57kAvSul66bprU',
    appId: '1:661720149477:ios:67acc5862ea348536c930c',
    messagingSenderId: '661720149477',
    projectId: 'nha-224',
    storageBucket: 'nha-224.firebasestorage.app',
    iosBundleId: 'com.example.depiFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtT4cE20y8zXptPBik-tABVpBaB6xNDEU',
    appId: '1:661720149477:web:3e9fbce7b1a22f946c930c',
    messagingSenderId: '661720149477',
    projectId: 'nha-224',
    authDomain: 'nha-224.firebaseapp.com',
    storageBucket: 'nha-224.firebasestorage.app',
    measurementId: 'G-58QZXTQ4E8',
  );
}
